# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11a39220d1b1165a131a3e3685b00db2277392d258f2d4e63266d88dfaf52b221efc5e942b70803cd31d76d51ed612978f32a74cc08252646e4c399e6638da3f

test:
  secret_key_base: 78016bbced2d1cbc48a5ac2b4b3bf609801d7d4ef6f18bd966ca71d944dc09f508479d15ee4bbaa51ce6097dad4a2fdf350bbadacd40064e8372ab3da1bb26c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
